-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\lab2_first_part\Sybsystem_FixPoint_pkg.vhd
-- Created: 2023-01-12 00:13:00
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Sybsystem_FixPoint_pkg IS
  TYPE vector_of_unsigned32 IS ARRAY (NATURAL RANGE <>) OF unsigned(31 DOWNTO 0);
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END Sybsystem_FixPoint_pkg;

